version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^.github:"
      - "^.vscode:"

archives:
  - format: zip
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_Windows_checksums.txt"

chocolateys:
  - name: azctx
    dependencies:
      - id: azure-cli
    owners: "Martin Brandl"
    authors: "Martin Brandl"
    url_template: "https://github.com/whiteducksoftware/azctx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    tags: "azctx azure cli"
    require_license_acceptance: true
    description: "Faster switching between Azure Subscriptions in your Azure CLI."
    api_key: "{{ .Env.CHOCO_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    project_url: "https://github.com/whiteducksoftware/azctx"
    license_url: "https://github.com/whiteducksoftware/azctx/blob/main/LICENSE"
    bug_tracker_url: "https://github.com/whiteducksoftware/azctx/issues"
    release_notes: "https://github.com/whiteducksoftware/azctx/releases/tag/{{ .Tag }}"
    copyright: "Copyright 2024 white duck GmbH"
