before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^.github:'
      - '^.vscode:'
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
brews:
  - name: azctx
    repository:
      owner: whiteducksoftware
      name: homebrew-tap
      branch: main
      token: "{{ .Env.AUTH_GITHUB }}"
    dependencies:
      - azure-cli
    url_template: "https://github.com/whiteducksoftware/azctx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Stefan Kürzeder
      email: stefan.kuerzeder@whiteduck.de
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/whiteducksoftware/azctx"
    description: "Faster switching between Azure Subscriptions in your Azure CLI."
    license: "MIT"
    install: |
      bin.install "azctx"
chocolateys:
  - name: azctx
    dependencies:
      - id: azure-cli
    owners: "Martin Brandl"
    authors: "Martin Brandl"
    url_template: "https://github.com/whiteducksoftware/azctx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    tags: "azctx azure cli"
    require_license_acceptance: true
    description: "Faster switching between Azure Subscriptions in your Azure CLI."
    api_key: "{{ .Env.CHOCO_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    project_url: "https://github.com/whiteducksoftware/azctx"
    license_url: "https://github.com/whiteducksoftware/azctx/blob/main/LICENSE"
    bug_tracker_url: "https://github.com/whiteducksoftware/azctx/issues"
    release_notes: "https://github.com/whiteducksoftware/azctx/releases/tag/{{ .Tag }}"
    copyright: "Copyright 2023 white duck GmbH"
