before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^.github:'
      - '^.vscode:'
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
brews:
  - name: azctx
    repository:
      owner: whiteducksoftware
      name: homebrew-tap
      branch: main
      token: "{{ .Env.AUTH_GITHUB }}"
    dependencies:
      - azure-cli
    url_template: "https://github.com/whiteducksoftware/azctx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Stefan Kürzeder
      email: stefan.kuerzeder@whiteduck.de
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/whiteducksoftware/azctx"
    description: "Faster switching between Azure Subscriptions in your Azure CLI."
    license: "MIT"
    install: |
      bin.install "azctx"
      