name: ci

on:
  pull_request:
      branches: [main]

env:
  GO_VERSION: '1.23.6'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: lint
        uses: golangci/golangci-lint-action@v6.3.0
        with:
          version: latest
          args: --issues-exit-code=1  --config=.golangci.yml

  ci-linux:
    name: ci-linux
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build with Goreleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --skip publish,archive,sbom,homebrew --clean --config .goreleaser.yaml

  ci-windows:
    name: ci-windows
    needs: ci-linux
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --skip publish,archive,sbom,chocolatey,winget --clean --config .goreleaser-windows.yaml
